/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SelectOrganisationImport } from './routes/select-organisation'
import { Route as IndexImport } from './routes/index'
import { Route as DiscoveryIndexImport } from './routes/discovery.index'
import { Route as DiscoveryOrganisationIdImport } from './routes/discovery.$organisationId'
import { Route as OrganisationsOrganisationSlugDashboardImport } from './routes/organisations.$organisationSlug.dashboard'

// Create/Update Routes

const SelectOrganisationRoute = SelectOrganisationImport.update({
  id: '/select-organisation',
  path: '/select-organisation',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DiscoveryIndexRoute = DiscoveryIndexImport.update({
  id: '/discovery/',
  path: '/discovery/',
  getParentRoute: () => rootRoute,
} as any)

const DiscoveryOrganisationIdRoute = DiscoveryOrganisationIdImport.update({
  id: '/discovery/$organisationId',
  path: '/discovery/$organisationId',
  getParentRoute: () => rootRoute,
} as any)

const OrganisationsOrganisationSlugDashboardRoute =
  OrganisationsOrganisationSlugDashboardImport.update({
    id: '/organisations/$organisationSlug/dashboard',
    path: '/organisations/$organisationSlug/dashboard',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/select-organisation': {
      id: '/select-organisation'
      path: '/select-organisation'
      fullPath: '/select-organisation'
      preLoaderRoute: typeof SelectOrganisationImport
      parentRoute: typeof rootRoute
    }
    '/discovery/$organisationId': {
      id: '/discovery/$organisationId'
      path: '/discovery/$organisationId'
      fullPath: '/discovery/$organisationId'
      preLoaderRoute: typeof DiscoveryOrganisationIdImport
      parentRoute: typeof rootRoute
    }
    '/discovery/': {
      id: '/discovery/'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryIndexImport
      parentRoute: typeof rootRoute
    }
    '/organisations/$organisationSlug/dashboard': {
      id: '/organisations/$organisationSlug/dashboard'
      path: '/organisations/$organisationSlug/dashboard'
      fullPath: '/organisations/$organisationSlug/dashboard'
      preLoaderRoute: typeof OrganisationsOrganisationSlugDashboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select-organisation': typeof SelectOrganisationRoute
  '/discovery/$organisationId': typeof DiscoveryOrganisationIdRoute
  '/discovery': typeof DiscoveryIndexRoute
  '/organisations/$organisationSlug/dashboard': typeof OrganisationsOrganisationSlugDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-organisation': typeof SelectOrganisationRoute
  '/discovery/$organisationId': typeof DiscoveryOrganisationIdRoute
  '/discovery': typeof DiscoveryIndexRoute
  '/organisations/$organisationSlug/dashboard': typeof OrganisationsOrganisationSlugDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/select-organisation': typeof SelectOrganisationRoute
  '/discovery/$organisationId': typeof DiscoveryOrganisationIdRoute
  '/discovery/': typeof DiscoveryIndexRoute
  '/organisations/$organisationSlug/dashboard': typeof OrganisationsOrganisationSlugDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/select-organisation'
    | '/discovery/$organisationId'
    | '/discovery'
    | '/organisations/$organisationSlug/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select-organisation'
    | '/discovery/$organisationId'
    | '/discovery'
    | '/organisations/$organisationSlug/dashboard'
  id:
    | '__root__'
    | '/'
    | '/select-organisation'
    | '/discovery/$organisationId'
    | '/discovery/'
    | '/organisations/$organisationSlug/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectOrganisationRoute: typeof SelectOrganisationRoute
  DiscoveryOrganisationIdRoute: typeof DiscoveryOrganisationIdRoute
  DiscoveryIndexRoute: typeof DiscoveryIndexRoute
  OrganisationsOrganisationSlugDashboardRoute: typeof OrganisationsOrganisationSlugDashboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectOrganisationRoute: SelectOrganisationRoute,
  DiscoveryOrganisationIdRoute: DiscoveryOrganisationIdRoute,
  DiscoveryIndexRoute: DiscoveryIndexRoute,
  OrganisationsOrganisationSlugDashboardRoute:
    OrganisationsOrganisationSlugDashboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/select-organisation",
        "/discovery/$organisationId",
        "/discovery/",
        "/organisations/$organisationSlug/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/select-organisation": {
      "filePath": "select-organisation.tsx"
    },
    "/discovery/$organisationId": {
      "filePath": "discovery.$organisationId.tsx"
    },
    "/discovery/": {
      "filePath": "discovery.index.tsx"
    },
    "/organisations/$organisationSlug/dashboard": {
      "filePath": "organisations.$organisationSlug.dashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
