/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExampleDashboardRouteImport } from './routes/example-dashboard'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverySwitchOrganisationRouteImport } from './routes/discovery.switch-organisation'
import { Route as DiscoverySelectOrganisationRouteImport } from './routes/discovery.select-organisation'
import { Route as DiscoveryOrganisationIdRouteImport } from './routes/discovery.$organisationId'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { ServerRoute as ApiAuthenticateServerRouteImport } from './routes/api/authenticate'

const rootServerRouteImport = createServerRootRoute()

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleDashboardRoute = ExampleDashboardRouteImport.update({
  id: '/example-dashboard',
  path: '/example-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverySwitchOrganisationRoute =
  DiscoverySwitchOrganisationRouteImport.update({
    id: '/discovery/switch-organisation',
    path: '/discovery/switch-organisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiscoverySelectOrganisationRoute =
  DiscoverySelectOrganisationRouteImport.update({
    id: '/discovery/select-organisation',
    path: '/discovery/select-organisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiscoveryOrganisationIdRoute = DiscoveryOrganisationIdRouteImport.update({
  id: '/discovery/$organisationId',
  path: '/discovery/$organisationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthenticateServerRoute = ApiAuthenticateServerRouteImport.update({
  id: '/api/authenticate',
  path: '/api/authenticate',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example-dashboard': typeof ExampleDashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/discovery/$organisationId': typeof DiscoveryOrganisationIdRoute
  '/discovery/select-organisation': typeof DiscoverySelectOrganisationRoute
  '/discovery/switch-organisation': typeof DiscoverySwitchOrganisationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example-dashboard': typeof ExampleDashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/discovery/$organisationId': typeof DiscoveryOrganisationIdRoute
  '/discovery/select-organisation': typeof DiscoverySelectOrganisationRoute
  '/discovery/switch-organisation': typeof DiscoverySwitchOrganisationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/example-dashboard': typeof ExampleDashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/discovery/$organisationId': typeof DiscoveryOrganisationIdRoute
  '/discovery/select-organisation': typeof DiscoverySelectOrganisationRoute
  '/discovery/switch-organisation': typeof DiscoverySwitchOrganisationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example-dashboard'
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/discovery/$organisationId'
    | '/discovery/select-organisation'
    | '/discovery/switch-organisation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/example-dashboard'
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/discovery/$organisationId'
    | '/discovery/select-organisation'
    | '/discovery/switch-organisation'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/example-dashboard'
    | '/login'
    | '/logout'
    | '/_authed/dashboard'
    | '/discovery/$organisationId'
    | '/discovery/select-organisation'
    | '/discovery/switch-organisation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ExampleDashboardRoute: typeof ExampleDashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  DiscoveryOrganisationIdRoute: typeof DiscoveryOrganisationIdRoute
  DiscoverySelectOrganisationRoute: typeof DiscoverySelectOrganisationRoute
  DiscoverySwitchOrganisationRoute: typeof DiscoverySwitchOrganisationRoute
}
export interface FileServerRoutesByFullPath {
  '/api/authenticate': typeof ApiAuthenticateServerRoute
}
export interface FileServerRoutesByTo {
  '/api/authenticate': typeof ApiAuthenticateServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/authenticate': typeof ApiAuthenticateServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/authenticate'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/authenticate'
  id: '__root__' | '/api/authenticate'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthenticateServerRoute: typeof ApiAuthenticateServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-dashboard': {
      id: '/example-dashboard'
      path: '/example-dashboard'
      fullPath: '/example-dashboard'
      preLoaderRoute: typeof ExampleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/switch-organisation': {
      id: '/discovery/switch-organisation'
      path: '/discovery/switch-organisation'
      fullPath: '/discovery/switch-organisation'
      preLoaderRoute: typeof DiscoverySwitchOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/select-organisation': {
      id: '/discovery/select-organisation'
      path: '/discovery/select-organisation'
      fullPath: '/discovery/select-organisation'
      preLoaderRoute: typeof DiscoverySelectOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/$organisationId': {
      id: '/discovery/$organisationId'
      path: '/discovery/$organisationId'
      fullPath: '/discovery/$organisationId'
      preLoaderRoute: typeof DiscoveryOrganisationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/authenticate': {
      id: '/api/authenticate'
      path: '/api/authenticate'
      fullPath: '/api/authenticate'
      preLoaderRoute: typeof ApiAuthenticateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ExampleDashboardRoute: ExampleDashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  DiscoveryOrganisationIdRoute: DiscoveryOrganisationIdRoute,
  DiscoverySelectOrganisationRoute: DiscoverySelectOrganisationRoute,
  DiscoverySwitchOrganisationRoute: DiscoverySwitchOrganisationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthenticateServerRoute: ApiAuthenticateServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
